version: '3'

services:
  mysqldb:
    container_name: mysql_ibrc
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ibrc
    volumes:
      - ./.docker/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ibrc
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80
    volumes:
     - /sessions
  web:
    build:
      context: .
    image: 'php:7.2-apache'
    container_name: ibrc
    # restart: always
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080
  # cloud9:
  #   image: sapk/cloud9
  #   volumes:
  #     - .:/workspace
  #   ports:
  #     - 8181:8181
  #   command: --auth username:password
